name: Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW32
        path-type: inherit
    - name: Install dependencies
      run: msys2do pacman -S --needed --noconfirm mingw-w64-i686-gcc mingw-w64-i686-wxWidgets mingw-w64-i686-boost
    - name: Create build files
      shell: cmd
      run: create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl
    - name: Symlink bfd.h
      run: msys2do ln -s /mingw32/include/binutils/bfd.h /mingw32/include/bfd.h
    - name: Symlink symcat.h
      run: msys2do ln -s /mingw32/include/binutils/symcat.h /mingw32/include/symcat.h
    - name: Symlink libbfd.a
      run: msys2do ln -s /mingw32/lib/binutils/libbfd.a /mingw32/lib/libbfd.a
    - name: Symlink libiberty.a
      run: msys2do ln -s /mingw32/lib/binutils/libiberty.a /mingw32/lib/libiberty.a
    - name: Workaround
      type: cmd
      run: msys2do "cd build/3.0/gmake && sed 's!\$(LDFLAGS) \$(RESOURCES) \$(ARCH) \$(LIBS)!\$(LIBS) \$(LDFLAGS) \$(RESOURCES) \$(ARCH)!g' *.make -i"
    - name: Add -lz
      type: cmd
      run: msys2do "cd build/3.0/gmake && sed 's!-lbfd!-lbfd -lz!g' *.make -i"
    - name: Build
      type: cmd
      run: msys2do "cd build/3.0/gmake && make config=release"
    - name: Package
      run: 7z a -r wxFormBuilder_win32.zip %cd%\output\*.* C:\msys64\mingw32\bin\libgcc*.dll C:\msys64\mingw32\bin\libstdc++*.dll C:\msys64\mingw32\bin\libwinpthread*.dll C:\msys64\mingw32\bin\libintl*.dll C:\msys64\mingw32\bin\libiconv*.dll C:\msys64\mingw32\bin\wx*.dll C:\msys64\mingw32\bin\libexpat*.dll C:\msys64\mingw32\bin\libjpeg*.dll C:\msys64\mingw32\bin\libpng*.dll C:\msys64\mingw32\bin\libtiff*.dll C:\msys64\mingw32\bin\zlib*.dll C:\msys64\mingw32\bin\libzstd*.dll C:\msys64\mingw32\bin\liblzma*.dll
    - name: Install InnoSetup
      run: cinst -y InnoSetup
    - name: Create installer
      run: '"C:\\Program Files (x86)\\Inno Setup 5\\ISCC.exe" wxFormBuilder.iss'
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: install\windows\wxFormBuilder*.exe
