name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW32
    - name: Install dependencies
      run: msys2do pacman -S --needed --noconfirm mingw-w64-i686-gcc mingw-w64-i686-wxWidgets mingw-w64-i686-boost make
    - name: Create build files
      shell: cmd
      run: create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl
    - name: Build
      run: msys2do ./.github/workflows/msys2.sh
    - name: Package
      shell: cmd
      run: 7z a -r wxFormBuilder_win32.zip %cd%\output\*.* d:\a\_temp\msys\msys64\mingw32\bin\libgcc*.dll d:\a\_temp\msys\msys64\mingw32\bin\libstdc++*.dll d:\a\_temp\msys\msys64\mingw32\bin\libwinpthread*.dll d:\a\_temp\msys\msys64\mingw32\bin\libintl*.dll d:\a\_temp\msys\msys64\mingw32\bin\libiconv*.dll d:\a\_temp\msys\msys64\mingw32\bin\wx*.dll d:\a\_temp\msys\msys64\mingw32\bin\libexpat*.dll d:\a\_temp\msys\msys64\mingw32\bin\libjpeg*.dll d:\a\_temp\msys\msys64\mingw32\bin\libpng*.dll d:\a\_temp\msys\msys64\mingw32\bin\libtiff*.dll d:\a\_temp\msys\msys64\mingw32\bin\zlib*.dll d:\a\_temp\msys\msys64\mingw32\bin\libzstd*.dll d:\a\_temp\msys\msys64\mingw32\bin\liblzma*.dll
    - name: Create installer
      shell: cmd
      run: '"C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" wxFormBuilder.iss'
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Windows
        path: install\windows\wxFormBuilder*.exe
